### PR TITLE
Switched build method to nw-builder

### PR DESCRIPTION
**Pull request by BoatsAreRockable**
Redone #149 in what I believe to be the correct manner. This changes the build method from using Web2Exe to nw-builder. Unlike #149 this is initially for v0.6.x and nw.js 0.12.3. 

Build instructions:
~~~
npm install evshiron/nw-builder -g
node build.js
~~~

### CODE REVIEW

**Comment by le717** [comment]
What all does this change bring, other than 0.13 support? Smaller binaries,  better binary stability or debugging? Easier building? Will we have to switch back to the other way in the future for some reason?  Is this a temporary measure? Explain why you think we need this change.

(I don't have any real objections here, but answer the questions as if I do. These are questions you will face in one form or another. ;))

**Comment by le717** [comment]
Also,  since this is for 0.6.x, I shall add it to the milestone.

**Comment by BoatsAreRockable** [comment]
@le717 I've pushed some changes. 

> Explain why you think we need this change.

Reasons I think we should switch to nw-builder (other then 0.13 support):
* Easier build process (one command)
* Makes it easy to preview the app (using the `-r` argument)
* I don't like how Web2Exe pollutes the `package.json` file with extra stuff.
* When #134 is fixed this could be added as a node dependency.

**Comment by le717** [comment]
Finish up 0.6.x, my man!

**Pull request merged**
