### PR TITLE
Restyle frame reel scroll bar #163

### PR DESCRIPTION
**Pull request by BoatsAreRockable**
This modifies the framereel's scrollbar to make it stand out less in the interface.

### CODE REVIEW

**Comment by le717** [comment]
Can you post a screenshot?

**Comment by BoatsAreRockable** [comment]
scrollbar changes

@le717 screenshot uploaded. (please excuse the state of my desk...)

**Comment by le717** [comment]
These also need changing on the launcher .)

**Comment by BoatsAreRockable** [comment]
index scrollbar

@le717 I've updated the launcher too now :)

**Comment by le717** [comment]
_Much_ better. :)

**Pull request merged**
